[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 100

[browser]
gatherUsageStats = false

[logger]
level = "info"
